# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import gRPC_pb2 as gRPC__pb2


class MyApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendDataToServer = channel.unary_unary(
                '/myapi.MyApi/SendDataToServer',
                request_serializer=gRPC__pb2.DataRequest.SerializeToString,
                response_deserializer=gRPC__pb2.DataResponse.FromString,
                )


class MyApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendDataToServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MyApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendDataToServer': grpc.unary_unary_rpc_method_handler(
                    servicer.SendDataToServer,
                    request_deserializer=gRPC__pb2.DataRequest.FromString,
                    response_serializer=gRPC__pb2.DataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'myapi.MyApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MyApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendDataToServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/myapi.MyApi/SendDataToServer',
            gRPC__pb2.DataRequest.SerializeToString,
            gRPC__pb2.DataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
