# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gRPC.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngRPC.proto\x12\x05myapi\"\xb3\x01\n\x0b\x44\x61taRequest\x12\x11\n\tMT_CODIGO\x18\x01 \x01(\x05\x12\x18\n\x10MT_IMPLEMENTACAO\x18\x02 \x01(\t\x12\x0e\n\x06MT_FQN\x18\x03 \x01(\t\x12\x11\n\tCF_CODIGO\x18\x04 \x01(\x05\x12\x11\n\tMT_PACOTE\x18\x05 \x01(\t\x12\x11\n\tMT_CLASSE\x18\x06 \x01(\t\x12\x11\n\tMT_METODO\x18\x07 \x01(\t\x12\x1b\n\x13MT_METODOSPLITCAMEL\x18\x08 \x01(\t\"\x1e\n\x0c\x44\x61taResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2D\n\x05MyApi\x12;\n\x10SendDataToServer\x12\x12.myapi.DataRequest\x1a\x13.myapi.DataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gRPC_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DATAREQUEST']._serialized_start=22
  _globals['_DATAREQUEST']._serialized_end=201
  _globals['_DATARESPONSE']._serialized_start=203
  _globals['_DATARESPONSE']._serialized_end=233
  _globals['_MYAPI']._serialized_start=235
  _globals['_MYAPI']._serialized_end=303
# @@protoc_insertion_point(module_scope)
